# Site settings
title: My awesome title
email: avildes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url:  "avildes.github.io/blog/" # the base hostname & protocol for your site
burl: "avildes.github.io/blog/"

twitter_username: jekyllrb
github_username:  jekyll

# é preciso analisar o funcionamento dos footer-links', disqus e analytics (svgs estao na pasta _include)

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: avildes/blog
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:



# Build settings
markdown: kramdown

paginate: 4

author: Your name

gems: [jekyll-paginate]
